[package]
name = "window"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.27.5", features = ["mint"] }
raw-window-handle = "0.5.0"
anyhow = "1.0.68"